import SwiftUI

/// The "Two of Us" brand mark, drawn in SwiftUI so it can animate: two overlapping
/// circles (the two parents) screen-blending over black into a bright shared glow,
/// with a warm point of light (the baby) at the heart. Matches the app-icon /
/// launch-logo artwork generated by `design/icon/generate_icons.py`.
struct CradleMark: View {
    /// Overall mark size in points (the launch logo ships at 240pt — match it for a
    /// seamless hand-off from the static launch screen).
    var size: CGFloat = 240
    /// Heartbeat scale applied to the baby light (1 = at rest).
    var babyScale: CGFloat = 1
    /// 0…1 bloom on the baby's soft glow.
    var glowOpacity: Double = 1

    // Geometry mirrors the generator constants (LEFT_C / RIGHT_C / BABY_C as
    // (x, y, r) fractions of the mark; +y is down). Deliberately not mirrored.
    private var babyDiameter: CGFloat { size * 0.164 }

    private let babyLight = Color(red: 1.0, green: 0.957, blue: 0.910) // #FFF4E8

    var body: some View {
        ZStack {
            // The two parents. `.screen` over the black backdrop reproduces the
            // bright blended lens where they overlap (same as the icon artwork).
            Circle()
                .fill(AppColor.accentSleep)            // periwinkle — left parent
                .frame(width: size * 0.500, height: size * 0.500)
                .offset(x: -size * 0.130, y: -size * 0.010)
                .blendMode(.screen)
            Circle()
                .fill(AppColor.accentFeed)             // teal — right parent
                .frame(width: size * 0.472, height: size * 0.472)
                .offset(x: size * 0.118, y: size * 0.010)
                .blendMode(.screen)

            // The baby — a warm point of light cradled low in the overlap, with a
            // soft glow bloom spilling down; offset to match the icon.
            ZStack {
                Circle()
                    .fill(babyLight)
                    .frame(width: babyDiameter * 2.0, height: babyDiameter * 2.0)
                    .blur(radius: babyDiameter * 0.55)
                    .opacity(0.55 * glowOpacity)
                Circle()
                    .fill(babyLight)
                    .frame(width: babyDiameter, height: babyDiameter)
            }
            .scaleEffect(babyScale)
            .offset(x: 0, y: size * 0.085)
        }
        .frame(width: size, height: size)
        .compositingGroup()
    }
}

/// The launch splash. Its first frame matches the static launch screen exactly
/// (centered mark on black), so the hand-off is seamless; it then gives the baby a
/// single gentle heartbeat + glow bloom, fades in the wordmark, and dismisses via
/// `onComplete`. Honors Reduce Motion by skipping the motion and just fading in.
struct SplashView: View {
    /// Called once the splash has finished; the host fades it away.
    var onComplete: () -> Void

    @Environment(\.accessibilityReduceMotion) private var reduceMotion

    @State private var babyScale: CGFloat = 1
    @State private var glowOpacity: Double = 0
    @State private var wordmarkOpacity: Double = 0
    @State private var wordmarkOffset: CGFloat = 6

    private let markSize: CGFloat = 240

    var body: some View {
        ZStack {
            Color.black.ignoresSafeArea()

            // Centered exactly like the launch logo (seamless hand-off).
            CradleMark(size: markSize, babyScale: babyScale, glowOpacity: glowOpacity)

            Text("Two of Us")
                .font(AppFont.hero(26, weight: .semibold))
                .foregroundStyle(.white)
                .opacity(wordmarkOpacity)
                .offset(y: markSize / 2 + 34 + wordmarkOffset)
        }
        .task { await run() }
    }

    @MainActor private func run() async {
        if reduceMotion {
            glowOpacity = 1
            withAnimation(.easeIn(duration: 0.3)) {
                wordmarkOpacity = 1
                wordmarkOffset = 0
            }
            try? await Task.sleep(for: .seconds(0.85))
            onComplete()
            return
        }

        // Bloom the glow, fade the wordmark up, and give one calm heartbeat.
        withAnimation(.easeInOut(duration: 0.6)) { glowOpacity = 1 }
        withAnimation(.easeOut(duration: 0.45).delay(0.45)) {
            wordmarkOpacity = 1
            wordmarkOffset = 0
        }
        withAnimation(.easeInOut(duration: 0.7).delay(0.15)) { babyScale = 1.07 }
        withAnimation(.easeInOut(duration: 0.5).delay(0.85)) { babyScale = 1.0 }

        try? await Task.sleep(for: .seconds(1.5))
        onComplete()
    }
}

#Preview {
    SplashView(onComplete: {})
}
