#!/bin/sh
#
# Shared logic for keeping MillerTime.xcodeproj in sync with project.yml.
#
# The .xcodeproj is generated by XcodeGen and is gitignored — git never
# updates it for you. After any checkout/merge/rebase that changes
# project.yml, the generated project is stale (this is what causes spurious
# "only available in iOS X or newer" errors when the deployment target moves).
# These hooks regenerate it automatically.
#
# Runs from the working-tree root (git sets cwd there before invoking hooks).

# Only act if this looks like the MillerTime project root.
[ -f project.yml ] || exit 0

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "⚠️  xcodegen not found — skipping project regeneration."
  echo "    Install it (brew install xcodegen) and run 'make project' to sync."
  exit 0
fi

echo "🛠  project.yml changed — regenerating Xcode project…"
xcodegen generate --quiet && echo "✅ MillerTime.xcodeproj is in sync with project.yml."
