import SwiftUI

/// The "Two of Us" brand mark, drawn in SwiftUI so it can animate: two overlapping
/// circles (the two parents) screen-blending over black into a bright shared glow,
/// with a warm point of light (the baby) at the heart. The geometry matches the
/// app-icon / launch-logo artwork generated by `design/icon/generate_icons.py`;
/// the in-app rendering is deliberately softer — feathered rims and pastel tints,
/// glowing lights rather than the icon's crisp vector discs.
///
/// Shared by the launch splash, the join flow, and the post-setup celebration. The `.screen` blend is isolated by the trailing
/// `compositingGroup`, but the artwork is designed for a dark backdrop — always
/// place the mark on a dark stage (splash stage, ink ambient, or stage halo).
struct CradleMark: View {
    /// Per-parent entrance transform: a drift `offset` (added to the resting
    /// offset), a `scale` (1 = resting), and an `opacity` (1 = present).
    /// `.identity` leaves the parent fully formed, so non-splash callers get the
    /// settled mark; the splash animates these to materialize the circles.
    struct ParentEntry: Equatable {
        var offset: CGSize = .zero
        var scale: CGFloat = 1
        var opacity: Double = 1
        static let identity = ParentEntry()
    }

    /// Overall mark size in points (the launch logo ships at 240pt — match it for a
    /// seamless hand-off from the static launch screen).
    var size: CGFloat = 240
    /// Heartbeat scale applied to the baby light (1 = at rest).
    var babyScale: CGFloat = 1
    /// 0…1 bloom on the baby's soft glow.
    var glowOpacity: Double = 1
    /// Entrance transform for the LEFT (periwinkle) parent. `.identity` = resting.
    var leftEntry: ParentEntry = .identity
    /// Entrance transform for the RIGHT (teal) parent. `.identity` = resting.
    var rightEntry: ParentEntry = .identity
    /// Reveal of the baby crisp core (0…1 opacity). 1 = present (default → unchanged).
    /// Separate from `glowOpacity` so the core can pop after the circles meet.
    var babyCoreOpacity: Double = 1

    // Geometry mirrors the generator constants (LEFT_C / RIGHT_C / BABY_C as
    // (x, y, r) fractions of the mark; +y is down). Deliberately not mirrored.
    private var babyDiameter: CGFloat { size * 0.164 }

    // AppColor accents lifted toward white for this glow rendering; the icon
    // keeps the saturated originals (crisp edges read correctly at icon size).
    private let leftTint  = Color(hex: "A0A0FF")  // from accentSleep #8E8EFF
    private let rightTint = Color(hex: "73D0C3")  // from accentFeed  #5AC8B8

    private let babyLight = AppColor.nightlightCream
    private let babyGlow  = Color(hex: "FFE9CF")  // glow runs warmer than the core

    /// Soft "nightlight" fill: a solid plateau so the disc still reads like the
    /// icon's, then a feathered rim instead of a hard vector edge. Cheaper than a
    /// blur and animates cleanly under the entrance `scaleEffect`.
    private func parentFill(_ tint: Color, radius: CGFloat) -> RadialGradient {
        RadialGradient(stops: [
            .init(color: tint,               location: 0.0),
            .init(color: tint,               location: 0.80),
            .init(color: tint.opacity(0.55), location: 0.92),
            .init(color: tint.opacity(0.0),  location: 1.0),
        ], center: .center, startRadius: 0, endRadius: radius)
    }

    var body: some View {
        ZStack {
            // The two parents. `.screen` over the black backdrop reproduces the
            // bright blended lens where they overlap (same as the icon artwork).
            // Each scales/fades around its own resting center, then offsets into
            // place — so they can drift in independently and converge.
            Circle()
                .fill(parentFill(leftTint, radius: size * 0.250))  // periwinkle — left parent
                .frame(width: size * 0.500, height: size * 0.500)
                .scaleEffect(leftEntry.scale)
                .opacity(leftEntry.opacity)
                .offset(x: -size * 0.130 + leftEntry.offset.width,
                        y: -size * 0.010 + leftEntry.offset.height)
                .blendMode(.screen)
            Circle()
                .fill(parentFill(rightTint, radius: size * 0.236)) // teal — right parent
                .frame(width: size * 0.472, height: size * 0.472)
                .scaleEffect(rightEntry.scale)
                .opacity(rightEntry.opacity)
                .offset(x: size * 0.118 + rightEntry.offset.width,
                        y: size * 0.010 + rightEntry.offset.height)
                .blendMode(.screen)

            // The baby — a warm point of light cradled low in the overlap, with a
            // soft glow bloom spilling down; offset to match the icon.
            ZStack {
                Circle()
                    .fill(babyGlow)
                    .frame(width: babyDiameter * 2.6, height: babyDiameter * 2.6)
                    .blur(radius: babyDiameter * 0.70)
                    .opacity(0.62 * glowOpacity)
                Circle()
                    .fill(babyLight)
                    .frame(width: babyDiameter, height: babyDiameter)
                    .opacity(babyCoreOpacity)
            }
            .scaleEffect(babyScale)
            .offset(x: 0, y: size * 0.085)
        }
        .frame(width: size, height: size)
        .compositingGroup()
    }
}

#Preview {
    ZStack {
        Color.black.ignoresSafeArea()
        CradleMark()
    }
}
