import SwiftUI

/// The "Two of Us" brand mark, drawn in SwiftUI so it can animate: two overlapping
/// circles (the two parents) screen-blending over black into a bright shared glow,
/// with a warm point of light (the baby) at the heart. Matches the app-icon /
/// launch-logo artwork generated by `design/icon/generate_icons.py`.
///
/// Shared by the launch splash, the onboarding welcome page, the join flow, and
/// the post-setup celebration. The `.screen` blend is isolated by the trailing
/// `compositingGroup`, but the artwork is designed for a dark backdrop — always
/// place the mark on a dark stage (splash stage, ink ambient, or stage halo).
struct CradleMark: View {
    /// Overall mark size in points (the launch logo ships at 240pt — match it for a
    /// seamless hand-off from the static launch screen).
    var size: CGFloat = 240
    /// Heartbeat scale applied to the baby light (1 = at rest).
    var babyScale: CGFloat = 1
    /// 0…1 bloom on the baby's soft glow.
    var glowOpacity: Double = 1
    /// Horizontal fly-in offset for the LEFT parent circle, in points, added on top
    /// of its resting offset. 0 = resting (default → unchanged for all callers).
    var leftEntryOffsetX: CGFloat = 0
    /// Horizontal fly-in offset for the RIGHT parent circle, in points, added on top
    /// of its resting offset. 0 = resting (default → unchanged for all callers).
    var rightEntryOffsetX: CGFloat = 0
    /// Reveal of the baby crisp core (0…1 opacity). 1 = present (default → unchanged).
    /// Separate from `glowOpacity` so the core can pop after the circles meet.
    var babyCoreOpacity: Double = 1

    // Geometry mirrors the generator constants (LEFT_C / RIGHT_C / BABY_C as
    // (x, y, r) fractions of the mark; +y is down). Deliberately not mirrored.
    private var babyDiameter: CGFloat { size * 0.164 }

    private let babyLight = Color(red: 1.0, green: 0.957, blue: 0.910) // #FFF4E8

    var body: some View {
        ZStack {
            // The two parents. `.screen` over the black backdrop reproduces the
            // bright blended lens where they overlap (same as the icon artwork).
            Circle()
                .fill(AppColor.accentSleep)            // periwinkle — left parent
                .frame(width: size * 0.500, height: size * 0.500)
                .offset(x: -size * 0.130 + leftEntryOffsetX, y: -size * 0.010)
                .blendMode(.screen)
            Circle()
                .fill(AppColor.accentFeed)             // teal — right parent
                .frame(width: size * 0.472, height: size * 0.472)
                .offset(x: size * 0.118 + rightEntryOffsetX, y: size * 0.010)
                .blendMode(.screen)

            // The baby — a warm point of light cradled low in the overlap, with a
            // soft glow bloom spilling down; offset to match the icon.
            ZStack {
                Circle()
                    .fill(babyLight)
                    .frame(width: babyDiameter * 2.0, height: babyDiameter * 2.0)
                    .blur(radius: babyDiameter * 0.55)
                    .opacity(0.55 * glowOpacity)
                Circle()
                    .fill(babyLight)
                    .frame(width: babyDiameter, height: babyDiameter)
                    .opacity(babyCoreOpacity)
            }
            .scaleEffect(babyScale)
            .offset(x: 0, y: size * 0.085)
        }
        .frame(width: size, height: size)
        .compositingGroup()
    }
}

#Preview {
    ZStack {
        Color.black.ignoresSafeArea()
        CradleMark()
    }
}
